#!/usr/bin/env python3
"""Write plugins/scsynth/Source/ScsyBuiltin.h: scsy's built-in SynthDef, compiled by nanosynth.

The drone csnd and fstr also play: a saw through a lowpass. The header is committed, so the build
does not need nanosynth.

usage: make scsy-builtin   (uv run --with nanosynth==0.4.0 python scripts/scsy_builtin.py)
"""

import pathlib

from nanosynth import synthdef
from nanosynth.ugens import LPF, Out, Saw

OUT = pathlib.Path(__file__).resolve().parents[1] / "plugins" / "scsynth" / "Source" / "ScsyBuiltin.h"

# ranges for p1..p3, as a sidecar .txt would give them
SPECS = """// @p1 pitch 110 880 Hz log
// @p2 level
// @p3 cutoff 1500 12000 Hz log
"""


@synthdef()
def builtin(pitch=110.0, level=0.0, cutoff=1500.0):
    sig = LPF.ar(source=Saw.ar(frequency=pitch), frequency=cutoff) * (0.3 * (0.15 + 0.85 * level))
    Out.ar(bus=0, source=[sig, sig])


def main() -> None:
    data = builtin.compile()
    rows = [", ".join(f"0x{b:02x}" for b in data[i : i + 16]) for i in range(0, len(data), 16)]
    body = ",\n    ".join(rows)
    OUT.write_text(
        "// Generated by scripts/scsy_builtin.py (make scsy-builtin). Do not edit.\n"
        "#pragma once\n\n"
        "namespace scsy {\n\n"
        f"static const unsigned char BUILTIN_DEF[{len(data)}] = {{\n    {body}\n}};\n\n"
        f'static const char* BUILTIN_SPECS = R"specs({SPECS})specs";\n\n'
        "}  // namespace scsy\n"
    )
    print(f"wrote {OUT} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
